swagger: '2.0'
info:
  title: API CAPPirote
  description: Generaci칩n autom치tica de documentaci칩n Swagger
  version: 1.0.0
host: localhost:3000
basePath: /
schemes:
  - http
tags:
  - name: devotos
  - name: eventos
  - name: usuario
  - name: imagenes
paths:
  /devotos:
    post:
      tags: 
        - devotos
      description: ''
      parameters:
        - name: authorization
          in: header
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              id_usuario:
                example: any
              id_hdad:
                example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    get:
      tags: 
        - devotos
      description: ''
      responses:
        '200':
          description: OK
  /devotos/user/{id_usuario}:
    get:
      tags: 
        - devotos
      description: ''
      parameters:
        - name: id_usuario
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /devotos/hdad/{id_hdad}:
    get:
      tags: 
        - devotos
      description: ''
      parameters:
        - name: id_hdad
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /devotos/comprobarrelacion:
    post:
      tags: 
        - devotos
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id_hdad:
                example: any
              id_usuario:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /devotos/:
    delete:
      tags: 
        - devotos
      description: ''
      parameters:
        - name: authorization
          in: header
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              id_hdad:
                example: any
              id_usuario:
                example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /eventos:
    post:
      tags: 
        - eventos
      description: ''
      parameters:
        - name: authorization
          in: header
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              nombre:
                example: any
              descripcion:
                example: any
              fecha:
                example: any
              id_usuario:
                example: any
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    get:
      tags: 
        - eventos
      description: ''
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /eventos/{id}:
    get:
      tags: 
        - eventos
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      tags: 
        - eventos
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              nombre:
                example: any
              descripcion:
                example: any
              fecha:
                example: any
              id_usuario:
                example: any
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    delete:
      tags: 
        - eventos
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: authorization
          in: header
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /images/{id_hdad}:
    post:
      description: ''
      parameters:
        - name: id_hdad
          in: path
          required: true
          type: string
        - name: authorization
          in: header
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              image_urls:
                example: any
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
    get:
      description: ''
      parameters:
        - name: id_hdad
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      description: ''
      parameters:
        - name: id_hdad
          in: path
          required: true
          type: string
        - name: authorization
          in: header
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              image_url:
                example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /hermandades:
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              nombre:
                example: any
              apelativo:
                example: any
              titulares:
                example: any
              fundacion:
                example: any
              sede:
                example: any
              dia:
                example: any
              itinerario:
                example: any
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    get:
      description: ''
      responses:
        '200':
          description: OK
  /hermandades/{id}:
    get:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              nombre:
                example: any
              apelativo:
                example: any
              titulares:
                example: any
              fundacion:
                example: any
              sede:
                example: any
              dia:
                example: any
              itinerario:
                example: any
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    delete:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /hermandades/dia/{dia}:
    get:
      description: ''
      parameters:
        - name: dia
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /hermandades/updatelocation:
    patch:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                example: any
              latitud:
                example: any
              longitud:
                example: any
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /hermandades/location/{id}:
    get:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /noticias:
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              titulo:
                example: any
              cuerpo:
                example: any
              fecha:
                example: any
              imagen:
                example: any
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    get:
      description: ''
      parameters:
        - name: page
          in: query
          type: string
        - name: limit
          in: query
          type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /noticias/search:
    get:
      description: ''
      parameters:
        - name: search
          in: query
          type: string
        - name: page
          in: query
          type: string
        - name: limit
          in: query
          type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /noticias/{id}:
    get:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              titulo:
                example: any
              cuerpo:
                example: any
              fecha:
                example: any
              imagen:
                example: any
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    delete:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /register:
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              nombre:
                example: any
              correo:
                example: any
              contrasena:
                example: any
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /login:
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              correo:
                example: any
              contrasena:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /usuarios:
    get:
      description: ''
      parameters:
        - name: authorization
          in: header
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /usuarios/{id}:
    get:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: authorization
          in: header
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: authorization
          in: header
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              nombre:
                example: any
              correo:
                example: any
              contrase침a:
                example: any
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    delete:
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: authorization
          in: header
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
